<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [4]:

# Your code here
def basic_stats(numbers):
    np_numbers=numpy.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

### 1.2 Named functions that don’t return

In [ ]:

# Your code here


### 1.3 Anonymous functions

In [ ]:

# Your code here


### 1.4 Optional arguments

In [ ]:

# Your code here


## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:

# Your code here


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

the return statement outside the if statement in the function serves the function of the else statement. 
If the condition of if statement is fulfilled, the if statement will be operated and return "Hello Batman! So, nice to meet you!". 
If the condition of if statement is not fulfilled, the if statement will be skipped. The function will return "Hello {name}!". 

## Exercise 2 :  Calculator functions

In [1]:



# Your solution here
import numpy as np
def add(x,y):
    return x + y

def subtract(x,y):
    return x-y

def multiply(x,y):
    return x*y

def divide(x,y):
    new_array = y==0
    if any(new_array):
        print (exit)
        exit()
    else:
        return x/y
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 0])
print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))

[100 100 100 100  27]
[-28 -32 -12  52  27]
[2304 2244 2464 1824    0]
None


In [4]:
import numpy as np
def add(x,y):
    return x + y

def subtract(x,y):
    return x-y

def multiply(x,y):
    return x*y

def divide(x,y):
    new_array = y==0
    if any(new_array):
        print (exit)
        exit()
    else:
        return x/y
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 0])
print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))

[100 100 100 100  27]
[-28 -32 -12  52  27]
[2304 2244 2464 1824    0]
error


## Exercise 3 :  max_info() with NumPy

In [20]:



# Your solution here
import numpy
def max_info(numbers):
    return (numpy.max(numbers),numpy.argmax(numbers))

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
max_info(numbers)

(83, 2)